tasks:
  - name: Setup
    init: |
      cd client
      npm init -y
      npm install
    command: |
      cp .env.SAMPLE .env
      # Make sure to replace 'YOUR_HEDERA_NETWORK_CREDENTIALS' with actual credentials or modify the setup to securely configure them.
      echo "Enter your Hedera network credentials in the .env file for testnet/mainnet."
